create table if not exists public.locations (
  id bigint generated by default as identity primary key,
  latitude double precision not null,
  longitude double precision not null,
  accuracy double precision,
  created_at timestamptz not null default now()
);

alter table public.locations enable row level security;

grant usage on schema public to anon;
grant insert on table public.locations to anon;
grant usage, select on sequence public.locations_id_seq to anon;

drop policy if exists "Allow public location inserts" on public.locations;
drop policy if exists "Allow public location reads" on public.locations;

create policy "Allow public location inserts"
on public.locations
for insert
to anon
with check (
  latitude between -90 and 90
  and longitude between -180 and 180
);
